### ISSUE TITLE
Wiki links being cut off

### ISSUE THREAD

**Issue by n0ided** [embolalia/willie#797] opened 2015-04-30 16:39 UTC
Example:
```
18:38 <@removed> .wik Zoological conspiracy theories involving Israel
18:38 <@removed> [WIKIPEDIA] Israel-related animal conspiracy theories | "Zoological conspiracy theories involving Israel are occasionally found in the media or on the internet, typically in Muslim
                majority countries, alleging use of animals by Israel to attack civilians or to conduct espionage. These conspiracies are often reported as evidence of a Zionist or Israeli plot..." |
                https://en.wikipedia.org/wiki/Israel-related_animal_conspiracy_theorie
```
Links are being cut off if the url is too big, this should get fixed

`Contributor's edit: I put the IRC paste into triple backticks to keep it's original format intact and un-tag the account named "removed"`

**Comment by embolalia** [comment] 2015-05-24 17:53
What version are you running? I can't reproduce this on 5.3.0 using that query. Is there another that will reproduce it?

**Comment by embolalia** [comment] 2015-07-11 12:53
Can not reproduce. Closing; reopen if you have more information.

**Closed by embolalia** 2015-07-11 12:53 UTC
Labels: Bug, Easyfix, needinfo
