### ISSUE TITLE
Willie shows "UnicodeDecodeError: 'ascii' codec can't decode byte ..." errors with extended unicodes in IRC.

### ISSUE THREAD

**Issue by antdude** [embolalia/willie#799] opened 2015-05-08 00:02 UTC
...
04:45PM <chainey> ant would say: ¿
04:45PM <Willie> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 59:
          ordinal not in range(128) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 135, in
          log_message)
04:46PM <Mousey> ⚥
04:46PM <Willie> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 43:
          ordinal not in range(128) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 135, in
          log_message)
04:46PM <chainey> Willie--
04:46PM <Mousey> dammit willie
04:46PM <Mousey> thanks
04:47PM <Mousey> now i have a bunch of numbers to memorize
04:47PM <Mousey> 00bf, good one
04:48PM <Mousey> ¿lo siento?
04:48PM <Willie> UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 43:
          ordinal not in range(128) (file
          "/usr/local/lib/python2.7/dist-packages/willie/modules/chanlogs.py", line 135, in
          log_message)
...

Why? Thank you in advance. :)

**Comment by tyrope** [comment] 2015-05-08 01:40
Duplicate of #768

**Closed by tyrope** 2015-05-08 01:40 UTC
