### ISSUE TITLE
Willie does not connect on versions > 4.6.0

### ISSUE THREAD

**Issue by RustyBower** [embolalia/willie#695] opened 2014-12-23 03:06 UTC
Tried connecting with 4.6.1, 4.6.2, and 5.0.0-beta.

Same configuration file, running willie.py out of the tar.gz directory.

Also tried generating a new config with each version, and disabling all the addons.

Working (4.6.0):
Registered 57 modules,
4 modules failed to load

Connecting to irc.xxxx.com:6697...
Connected.

Not Working (4.6.1+):
Registered 57 modules,
4 modules failed to load

Connecting to irc.xxxx.com:6697...
Connected.

But it just sits there.

A tcpdump shows that traffic is happening, but the bot doesn't join the channel, or join the server (since I have oper and I can see connected clients)

**Comment by embolalia** [comment] 2015-01-01 05:09
@blixnood, calling something someone said dumb is entirely unproductive. Moreover, @elad661 is a volunteer, as is everyone else here. While we want to provide good software, none of us is under any obligation to ensure it works in any specific situation. If @elad661 doesn't want to test against a specific network, that is entirely his decision.

To be clear, optimally this bot will connect to any server which follows the appropriate specifications. There are any number of reasons why some of the volunteers for this project might not be able to or want to connect to some of them. The best thing to do when this happens is to give us as much information as you can about the server in question - like, for example, what version of what daemon it's running. :+1: to @subterfugium for providing that.

I'm unlocking discussion on this. I trust that it will be confined to the technical matters at hand.

**Comment by elad661** [comment] 2015-01-01 08:47
Fix it yourself, I'm not going to waste my time on this issue.

**Comment by Khabi** [comment] 2015-01-02 04:44
To the original issue @RustyBower 
I was able to successfully connect with both the 4.6 branch and the master branch from git.  However I have an idea of what is actually going on.  

If I get a copy of willie and run it from the install directory it does not work and presents the issues that people are seeing.  If you actually do the install process "python setup.py install"  and run willie from your path, it works correctly.   So I would say to do an actual install and try again.

I believe this will fix the issue with @subterfugium  as well.

**Comment by RustyBower** [comment] 2015-01-04 20:34
Unfortunately I am still getting the same issue (with git branch).

ubuntu@ip-10-1-2-3:/opt/willie$ willie

Welcome to Willie. Loading modules...


Error in safety setup procedure: ConfigurationError: Safety module not configured (modules/safety.py:55)
Setting up CalcBucket...
CalcBucket test item:
[{'item_value': u'http://i.imgur.com/0L5c5e6.jpg', 'item_key': u'Athehomedepot', 'nick': u'chugdiesel'}]
Done setting up CalcBucket!
Error in karma setup procedure: 'WillieDB' object has no attribute 'karma' (../../../../../../home/ubuntu/.willie/modules/karma.py:71)
Setting up Bucket...
Done setting up Bucket!


Registered 60 modules,
2 modules failed to load


Connecting to irc.129irc.com:6697...
Connected.
/usr/local/lib/python2.7/dist-packages/willie/tools.py:282: UserWarning: debugwill be removed in Willie 5.0. Please see http://willie.dftba.net/willie_5.html for more info.
  warnings.warn(thing + 'will be removed in Willie 5.0. Please see '
[irc.pyc] Closing Link: BotSaget[1.2.3.4] (Ping timeout: 35 seconds)
Calling shutdown for 4 modules.
calling reddit.shutdown
calling youtube.shutdown
calling bugzilla.shutdown
Error calling shutdown method for module bugzilla:None
calling github.shutdown
Closed!
Warning: Disconnected. Reconnecting in 20 seconds...

From raw.log:
>>1420403551.2	NICK BotSaget
>>1420403551.2	USER willie +iw BotSaget :Willie Embosbot, http://willie.dftba.net
>>1420403551.2	CAP LS
<<1420403551.28	:ec2east.129irc.com NOTICE AUTH :*** Looking up your hostname...
<<1420403551.28	:ec2east.129irc.com NOTICE AUTH :*** Found your hostname (cached)
<<1420403551.36	PING :20E7964D
>>1420403551.36	PONG 20E7964D
<<1420403551.43	:ec2east.129irc.com CAP BotSaget LS :account-notify away-notify multi-prefix tls userhost-in-names
<<1420403586.37	ERROR :Closing Link: BotSaget[54.214.137.71] (Ping timeout: 35 seconds)

**Comment by RustyBower** [comment] 2015-01-04 22:25
Looks like the issue comes from this:

https://github.com/embolalia/willie/blob/master/willie/irc.py#L300

Commenting out that line fixes things.

**Comment by embolalia** [comment] 2015-01-06 02:58
I had figured it was related to CAP LS (we can't just remove that as a complete solution, since that would break all sorts of IRCv3 stuff). The odd thing is, irc.irc129.com (or at least ec2east.129irc.com) is running Unreal 3.2.10. ftl.dftba.net (and I think the rest of irc.dftba.net) is Unreal 3.2.9. Still doesn't explain the ZNC problem, but I might be able to look into the difference in the Unreal versions to find the cause.

**Comment by RustyBower** [comment] 2015-01-06 03:17
Ah. I'll get those versions sync'd up and I'll test again

**Comment by embolalia** [comment] 2015-01-06 12:03
Looks like we weren't waiting quite long enough to send that; putting it after connection registration seems to work on newer Unreals. @RustyBower, should be fixed for you. @subterfugium, can you confirm this works for you on ZNC?

**Comment by RustyBower** [comment] 2015-01-06 20:14
Seems like things are good now, at least for me (other people might be having issues, so not gonna close this out)

**Comment by subterfugium** [comment] 2015-01-07 08:01
@embolalia @elad661 @Khabi The connection to ZNC with today's master branch does work indeed. Thank you :)

ZNC configured with DV cert and
```
SSLCiphers = AES256+EECDH:AES256+EDH:!aNULL
SSLProtocols = TLSv1.1 TLSv1.2
IPv4 = true
IPv6 = false
Port = xxxxx
SSL = true
```

**Comment by tyrope** [comment] 2015-01-07 17:12
Apparently this is still an issue on EsperNET
```
[1809.22] <flashcactus> 5.0 flat-out refuses to connect properly.
[1809.39] <flashcactus> I think I posted something the issue.
[1809.47] <flashcactus> *regarding the
[1809.49] <@Tyrope> That issue is fixed iirc.
[1810.02] <@Tyrope> Assuming you mean this one
[1810.04] <@Tyrope> .findbug 695
[1810.06] <Willie> Tyrope: [#695]title: Willie does not connect on versions > 4.6.0 | Tried connecting with 4.6.1, 4.6.2, and 5.0.0-beta....
[1810.07] <Willie> https://github.com/embolalia/willie/issues/695
[1810.15] <flashcactus> No, it just stalls a bit farther.
[1810.57] <@Tyrope> Which network is this?
[1811.11] <flashcactus> It doesn't get disconnected for not replying to the first ping, but it doesn't proceed to join the channels either.
[1811.16] <flashcactus> irc.esper.net
```

**Comment by flashcactus** [comment] 2015-01-07 18:08
Relevant log for willie at commit 37cbda4: 
```
>>1420650355.4041085    NICK Kountdown
>>1420650355.4272435    USER kountdown +iw Kountdown :Kountdown Willievich Cactusoff, http://github.com/flashcactus/kountdown/
>>1420650355.4300363    CAP LS
<<1420650355.5431767    :calamity.esper.net NOTICE * :*** Looking up your hostname...
<<1420650355.658895     :calamity.esper.net NOTICE * :*** Checking Ident
<<1420650355.6597586    :calamity.esper.net NOTICE * :*** No Ident response
<<1420650355.8040738    :calamity.esper.net NOTICE * :*** Couldn't look up your hostname
<<1420650355.919851     PING :00D6D190
>>1420650355.9200718    PONG 00D6D190
<<1420650355.9208632    :calamity.esper.net CAP Kountdown LS :account-notify away-notify extended-join multi-prefix sasl tls
<<1420650409.6176783    ERROR :Closing Link: 2a00:ab00:10b:46:182:30:120:0 (Connection timed out)
```

**Comment by embolalia** [comment] 2015-01-11 01:57
Could not reproduce on irc.esper.net or calamity.esper.net at 16a4fb64e7f377016de41d44c5882b56edd432d0. Is this still happening?

**Comment by embolalia** [comment] 2015-01-11 15:24
It seems this change breaks SASL auth, since [`AUTHENTICATE` has to happen before connection registration](https://github.com/ircv3/ircv3-specifications/blob/master/extensions/sasl-3.1#L20). This will need more investigation.

**Comment by embolalia** [comment] 2015-01-11 15:31
@Khabi I believe this is related to your PR #692. You mentioned being able to replicate it on multiple servers; could you get me a list so I can verify?

**Comment by Khabi** [comment] 2015-01-11 20:30
@embolalia one was freenode itself, and the other was a personal IRC server running ircd-hybrid 7.2.3 (I can give you the details on it privately if you want, I don't want to plaster it on the web).

I did a bit more testing afterwards, and I *think* it was related to a end irc server taking to long to get a ident response.  The network I was on I suspect was just letting the request timeout instead of rejecting it. Equiv of doing "iptables -A INPUT -i $IFACE -p tcp --dport 113 -j DROP" instead of "iptables -A INPUT -i $IFACE -p tcp --dport 113 -j REJECT"

I have a bit of spare time today, I'll see if I can replicate it.

**Comment by elad661** [comment] 2015-01-11 20:41
I didn't know IRC networks that used ident still exist, it is pretty much useless in the age where most actual users are behind some sort of NAT or CGNAT.

I am 100% sure freenode doesn't require ident, because my firewall is not configured to allow this port in and I don't run an ident daemon, yet I connect to freenode with no problems.

**Comment by Khabi** [comment] 2015-01-12 04:55
I've tried today and I've been unable to replicate it from my home machine, so I'm not really sure what to make of it.  My initial assumption (it was a quick one, I didn't do any in depth troubleshooting) was that ident was taking to long to timeout (even if not required) and on the server side it was possibly running into some kind of session timeout or something.  I did some iptables trickery to see if I could reproduce it, but got nowhere.

The odd part about all of this, is obviously on some networks moving the CAP later on works see @subterfugium @RustyBower  and my test cases on pull https://github.com/embolalia/willie/pull/692. Of course as @embolalia pointed out that breaks sasl connections now.

The best I can come up with without reading all of the IRC RFC is that maybe it has something to do with IPV6 (I see that in a few of the logs here) and CAP.  Honestly, that seems silly.  

If I get some time tomorrow I'll try to replicate the issue again from the same network I originally had the issues on.  Maybe I'll do some tcpdumps and see if anything else pops out.

**Comment by lkarsten** [comment] 2015-01-14 21:24
I ran into a similar issue today. Latest git 2a93da against Espernet.

Connect appeared to work fine, the bot joins the (single) configure channel, but it otherwise unresponsive. After a while it reconnects after logging a timeout on the console.

IRC server was availo.esper.net.

I got this working through hard-coding the ipv4 address of the irc server, forcing it to connect over IPv4.

**Comment by embolalia** [comment] 2015-01-15 01:08
@lkarsten, the failures here happen before JOIN is sent out at all, so if it's joining a channel you have a different issue. Please file a separate bug, including appropriate logs of your error. The issue in this bug appears to have been resolved, so I'm closing it.

**Closed by embolalia** 2015-01-15 01:08 UTC
Labels: Bug, needinfo
