### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 43: ordinal not in range(128) (file "/home/w/willie/willie/modules/chanlogs.py", line 135, in log_message)

### ISSUE THREAD

**Issue by n0ided** [embolalia/willie#798] opened 2015-04-30 18:10 UTC
Not sure what's causing this, seems like people has had this issue before.

**Comment by tyrope** [comment] 2015-04-30 19:53
Duplicate of #768

**Closed by tyrope** 2015-04-30 19:53 UTC
