### ISSUE TITLE
Extended latin character causing logging errors after upgrade

### ISSUE THREAD

**Issue by fiernot** [embolalia/willie#800] opened 2015-05-08 12:29 UTC
After upgrading to `Willie v. 5.3.0-git at commit: 5a64dd46925795a507150244ca0f4c024ee47210` we started to notice a problem when using extended latin characters, for example:

ñ, á,é,í,ó,ú

This was not happening previous to the upgrade. When using any of these characters and having willie to log channel messages, the following error message is seen:

`UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 41: ordinal not in range(128) (file "/usr/home/user/src/willie/willie/modules/chanlogs.py", line 135, in log_message)`

The line is not logged when this happens.

I have Willie running under FreeBSD 10.1-RELEASE-p9 and Python 2.7.8

**Comment by fiernot** [comment] 2015-05-08 12:33
It might be cause by commit afd7444443738275cc1ba6b03f5e2d6b35d89208

**Comment by tyrope** [comment] 2015-05-08 16:25
Duplicate of #768

**Closed by tyrope** 2015-05-08 16:25 UTC

**Comment by antdude** [comment] 2015-08-07 23:28
Why is v5.x still getting updates?
