### ISSUE TITLE
Logging broken for channels that contain /

### ISSUE THREAD

**Issue by mshade** [embolalia/willie#740] opened 2015-02-13 00:39 UTC
Willie spews errors when trying to log channel activity for channels that contain a '/' in the name. It interprets the / in the channel name as a subdirectory when trying to write.

For example, in the channel #r/linux on freenode:

```
IOError: [Errno 2] No such file or directory: u'/home/willie/chanlogs/r/linux-2015-02-13.log' (file "/home/willie/willie/willie/modules/chanlogs.py", line 113, in log_message)

**Comment by embolalia** [comment] 2015-02-13 01:25
Duplicate of #490.

**Closed by embolalia** 2015-02-13 01:25 UTC

**Comment by mshade** [comment] 2015-02-13 01:52
Apologies, searching for '/' is a little difficult :)
