### ISSUE TITLE
Willie.say doesn't print a string

### ISSUE THREAD

**Issue by pfcode** [embolalia/willie#739] opened 2015-02-12 21:09 UTC
Hi!
I have a little problem with my code. I parse SQL table using PyMySQL and I try to write data on IRC channel, but there's no output. I also tried to display the same string using print() in console... and it worked. Is it a willie.say() related issue or do I need to encode my string in some way before putting it as an argument to a function?

```python
def thread_check(willie, trigger):
        conn = pymysql.connect( ... )
        query = ... % (thread_check.lastTID)
        cur = conn.cursor()
        cur.execute(query)
        for r in cur:
                link = "http://starepro.info/forum/viewtopic.php?id=%d" % (r[0])
                msg = "[NEW THREAD] %s [Author: %s | Link: %s]" % (r[2], r[1], link)
                willie.say(msg)
                print(msg)
                thread_check.lastTID = r[0]
        return

thread_check.lastTID = 0
thread_check.commands = ['dd']
thread_check.priority = 'high'
```

I replaced SQL credentials and a query with "...". I'm sure they're valid.

**Comment by embolalia** [comment] 2015-02-12 23:47
Where did you get this way of writing modules? I don't mean to be snarky; there's some stuff here that's been deprecated for years, and if there's documentation suggesting it, that documentation needs to be fixed. Check out the wiki for newer documentation.

That said, this all looks like it should more or less work. Is there anything in any of the logs? What version are you on?

**Comment by tyrope** [comment] 2015-02-13 07:33
On line 7, `(r[0])` should be `(r[0],)`, note the comma. Otherwise it might not parse as a tuple.

As for the rest of the code, please update to the Willie5 standard, [See here](https://github.com/embolalia/willie/wiki/Willie-tutorial,-Part-2).

**Comment by pfcode** [comment] 2015-02-13 20:50
@embolalia, well, I wrote the part of this module a long time ago (there are other commands defined in the same file). I'm using Willie 5.0.0. The only thing that appends to output is a message from print() method: 
```
[NEW THREAD] Random subject [Author: Some user | Link: http://starepro.info/forum/viewtopic.php?id=12345]
```

@tyrope, adding a comma in that place gave no results. Issue was still there.

I moved the code into a separate file, which looks as below. Also, I've tried to use Template to append variable values to the string. Unfortunately, the module behaves exactly same as before :(
```python
import willie.module
import pymysql
import time
import string
from string import Template

@willie.module.commands('check')
def thread_check(bot, trigger):
        conn = pymysql.connect( ... )
        query = ... % (thread_check.lastTID)
        cur = conn.cursor()
        cur.execute(query)
        for r in cur:
                t = Template('[NEW THREAD] $subject [Author: $author | Link: http://starepro.info/forum/viewtopic.php?id=$id]')
                msg = t.substitute(id = r[0], subject = r[2], author = r[1])
                bot.say(msg)
                print(msg)
                thread_check.lastTID = r[0]
        return
thread_check.lastTID = 0
```

I also found that when I remove slash '/' and question mark '?' from the string it will work properly and will give an output to the IRC channel. For example,
```python
 t = Template('[NEW THREAD] $subject [Author: $author | Link: http:starepro.infoforumviewtopic.phpid=$id]')
```

**Comment by embolalia** [comment] 2015-02-21 19:24
I still can't reproduce this. Try to reduce this to the smallest piece of failing code possible. If you replace the database call with just setting it equal to what you expect the result to be, does it still fail? If so, what if you replace the entire message with just the string you expect the message to be? I need something that I'll be able to run on my own, which doesn't depend on your specific database and such, that causes the error.

**Comment by elad661** [comment] 2015-04-18 16:20
Since this is was marked as "needinfo" since February, and we're in April already, I'm closing this issue. It may be re-opened when the required information is provided.

**Closed by elad661** 2015-04-18 16:20 UTC
Labels: needinfo
