### ISSUE TITLE
Unable to obtain op

### ISSUE THREAD

**Issue by rinzes** [embolalia/willie#754] opened 2015-02-25 18:55 UTC
I am cfg as owner and willie has op. When I do .op I get KeyError: Identifier('dutch') (file "/usr/local/lib/python2.7/dist-packages/willie/modules/adminchannel.py", line 34, in op)

**Comment by tyrope** [comment] 2015-02-25 19:08
Duplicate of issue #734, which is an issue you created and has been fixed. Please confirm you have updated to at least the commit that fixed this.

**Comment by rinzes** [comment] 2015-02-25 19:15
I have upgraded to 5.1.1

**Comment by rinzes** [comment] 2015-02-25 19:16
you can close this issue... I've been corrected in my understanding how this is suppose to work

**Comment by janandjohn3** [comment] 2015-02-25 19:18
Just so I can look at why this is outputting a KeyError, can you tell us
the channel name you are running this in? Something may be screwing up the
checks for the privileges dict.

John Lage

**Comment by rinzes** [comment] 2015-02-25 20:37
Irc.efnet.org #inews

**Closed** 2015-02-25 21:07 UTC
Labels: needinfo
